apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - secrets.yaml

# 変数定義
vars:
  - name: TEAM_NAME
    objref:
      kind: Deployment
      name: backend
      apiVersion: apps/v1
