apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: $(TEAM_NAME)
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 205930621170.dkr.ecr.ap-northeast-1.amazonaws.com/challenge-cup-frontend-teamx:latest
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        - name: NODE_ENV
          value: "production"
        - name: NEW_RELIC_APP_NAME_FRONTEND
          value: "Challenge Cup Frontend $(TEAM_NAME)"
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: newrelic-frontend-secrets
              key: license_key
        - name: NEW_RELIC_BROWSER_KEY
          valueFrom:
            secretKeyRef:
              name: newrelic-frontend-secrets
              key: browser_key
        - name: NEW_RELIC_DISTRIBUTED_TRACING_ENABLED
          value: "true"
        - name: NEW_RELIC_LOG_LEVEL
          value: "info"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: $(TEAM_NAME)
  labels:
    app: frontend
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3001
  selector:
    app: frontend
  type: ClusterIP