# データベース接続エラーのアラート設定
---
apiVersion: monitoring.newrelic.com/v1alpha1
kind: AlertPolicy
metadata:
  name: challenge-cup-backend-alerts
  namespace: newrelic
spec:
  name: "Challenge Cup Backend Alerts"
  incidentPreference: "PER_CONDITION"
  pagerDutyIntegration:
    serviceKey:
      valueFrom:
        secretKeyRef:
          name: pagerduty-secrets
          key: backend_integration_key
  conditions:
    - name: "Database Error Rate"
      type: "apm_app_metric"
      metric: "datastore.error.count"
      entities:
        - "Challenge Cup Backend"
      threshold: 1
      duration: 5
      operator: "above"
      priority: "critical"
    - name: "Database Response Time"
      type: "apm_app_metric"
      metric: "datastore.duration"
      entities:
        - "Challenge Cup Backend"
      threshold: 1000  # ミリ秒単位
      duration: 5
      operator: "above"
      priority: "warning"
    - name: "Prisma Database Connection Errors"
      type: "nrql_alert"
      nrql:
        query: "SELECT count(*) FROM Transaction WHERE appName = 'Challenge Cup Backend' AND databaseCallCount > 0 AND error IS TRUE AND error.message LIKE '%prisma%connection%'"
      threshold: 1
      thresholdDuration: 60
      thresholdOccurrences: "at_least_once"
      operator: "above"
      priority: "critical"
