apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - namespace.yaml

replacements:
  - source:
      kind: Namespace
      name: teamx
      fieldPath: metadata.name
    targets:
      - select:
          kind: Deployment
          name: backend
        fieldPaths:
          - metadata.namespace
      - select:
          kind: Service
          name: backend
        fieldPaths:
          - metadata.namespace
images:
  - name: BACKEND_IMAGE
    newName: 205930621170.dkr.ecr.ap-northeast-1.amazonaws.com/challenge-cup-backend-teamx
    newTag: latest
