apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - configmap.yaml

replacements:
  - source:
      kind: ConfigMap
      name: team-backend
      fieldPath: data.name
    targets:
      - select:
          kind: Deployment
          name: backend
        fieldPaths:
          - metadata.namespace
      - select:
          kind: Service
          name: backend
        fieldPaths:
          - metadata.namespace
      - select:
          kind: Deployment
          name: backend-deployment
        fieldPaths:
          - spec.template.spec.containers.[name=backend].env.[name=NEW_RELIC_APP_NAME_BACKEND].value
        options:
          delimiter: "__TEAM__"
          index: 1
