name: Docker Build and Push

on:
  push:
    branches: [ main ]
    # paths:
    #   - 'frontend/**'
    #   - 'backend/**'
    #   - '.github/workflows/**'

env:
  AWS_REGION: ap-northeast-1
  TEAM_NAME: teamx

permissions:
  id-token: write
  contents: read

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push frontend image to Amazon ECR
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/challenge-cup-frontend-${{ env.TEAM_NAME }}:${{ github.sha }}
            ${{ steps.login-ecr.outputs.registry }}/challenge-cup-frontend-${{ env.TEAM_NAME }}:latest
          build-args: |
            NEW_RELIC_APP_NAME_FRONTEND=${{ secrets.NEW_RELIC_APP_NAME_FRONTEND }}
            NEW_RELIC_LICENSE_KEY=${{ secrets.NEW_RELIC_LICENSE_KEY }}
            NEW_RELIC_BROWSER_KEY=${{ secrets.NEW_RELIC_BROWSER_KEY }}

      - name: Debug build args
        run: |
          echo "Checking if New Relic license key is set"
          if [ -n "${{ secrets.NEW_RELIC_LICENSE_KEY }}" ]; then
            echo "License key is set"
          else
            echo "License key is not set"
          fi

  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Debug build args
        run: |
          echo "Checking if New Relic license key is set"
          if [ -n "${{ secrets.NEW_RELIC_LICENSE_KEY }}" ]; then
            echo "License key is set"
          else
            echo "License key is not set"
          fi

      - name: Build, tag, and push backend image to Amazon ECR
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/challenge-cup-backend-${{ env.TEAM_NAME }}:${{ github.sha }}
            ${{ steps.login-ecr.outputs.registry }}/challenge-cup-backend-${{ env.TEAM_NAME }}:latest
          build-args: |
            NEW_RELIC_APP_NAME_BACKEND=${{ secrets.NEW_RELIC_APP_NAME_BACKEND }}
            NEW_RELIC_LICENSE_KEY=${{ secrets.NEW_RELIC_LICENSE_KEY }}
            NEW_RELIC_BROWSER_KEY=${{ secrets.NEW_RELIC_BROWSER_KEY }}
